# -*- coding: utf-8 -*-
"""Google_Drive_Mount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WEgcU3wYfydN5O3vwn1j9_OO1IShlblv

**Google Drive에 있는 파일을 마운트**
<br/> 파일 > 드라이브 마운트 > 코드 실행
<br/> > 액세스 코드 발급 및 입력 
<br/> > 드라이브에 있는 파일 경로로 load
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('./drive/My Drive/housing.csv', 
                 header=None, delim_whitespace=True)
df.head()